### ISSUE TITLE
alternative use of  dinputto8

### ISSUE THREAD

**Issue by luca2125** [elishacloud/dinputto8#11]
Hi,

I like to add force feedback support to some games that not support it.

Many old and not old games have already the file dinput.dll on folder.

Therically I need to create a DLL proxy and rederect to original renamed DLL ( dinput_ori.dll ).

I don't have too much exprerience in DLL proxy.

Frankly I searching for a more elegant way to do it.

I ask if possible work directly with your project and avoid to create a a sort of dinput_ori.dll to put in the game forlder.

Do you think is possible and it is a good idea ?

Thank you !

**Comment by elishacloud** [comment]
There is a pretty easy way to proxy to another dll.  You can use my [DirectX-Wrappers](https://github.com/elishacloud/DirectX-Wrappers) project to wrap the DirectInput APIs.

Change [these lines](https://github.com/elishacloud/DirectX-Wrappers/blob/0128d420d408e16c403bcc2493ae8c7f2dee3c1b/dinput/dllmain.cpp#L37-L42) to this:

```c++
dinputdll = LoadLibraryA("dinput_ori.dll");
```

Then rename the original DLL to `dinput_ori.dll` and copy over the `dinput.dll` file created from the DirectX-Wrappers project.

For force feedback you would need to create a DirectInput effect.  See [this page](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ee417563(v=vs.85)) for details.

The hard part here would be knowing when to trigger the force feedback.  That would likely require custom coding per-game.

**Comment by elishacloud** [comment]
Closing issue.
