### ISSUE TITLE
FYI - Fixes Star Wars Episode 1 Racer Startup Crashes

### ISSUE THREAD

**Issue by kevinmarchant** [elishacloud/dinputto8#16]
Hi Elisha
Just a quick thank-you for DINPUTTO8.  A load of people (myself included) had problems with SWEp1Racer on PC (both CD and GOG versions), and your replacement DINPUT.DLL fixes it very nicely :-)  Suggest you add the game to the list of fixed games so others might stumble across this solution too (and sell it to GOG :-) )

**Comment by elishacloud** [comment]
Thanks for the comment.  I am glad to hear that this is helping users!

**Comment by IGx89** [comment]
Was the perfect fix for me for the Steam version as well, thank you!!

**Comment by elishacloud** [comment]
Closing issue.
