### ISSUE TITLE
Does not work well with European Air War

### ISSUE THREAD

**Issue by RealDrJester** [elishacloud/dinputto8#17]
The dll does not seem to work properly on EAW. It passes through to the native or third party input8.dll, but it doesn't seem to report the joysticks properly to the game itself. 

For instance, what joystick it detects it doesn't seem to respond to inputs. And this is true for native input8.dll or third party input8.dll like devreorder. 

Taking the dinput.dll out the game detects the joysticks and respond to it.

**Comment by CookiePLMonster** [comment]
Can you re-test with the latest version?

**Comment by elishacloud** [comment]
Closing as no response.  Reopen if there is still an issue here.
