### ISSUE TITLE
STCC/STCC2/V8 Challenge/Rally Masters think buttons are pressed continuously

### ISSUE THREAD

**Issue by CookiePLMonster** [elishacloud/dinputto8#19]
I don't have specific info yet and it might not even be a dinputto8 bug, as I am running these games from within Sandboxie **and** I literally can't run these games without dinputto8 - but it seems like they think Button 8 (Start button on my Xbone pad?) is continuously pressed. Pressing and releasing it, or pressing other buttons has no effect, and so effectively I am unable to find gamepad buttons.

These afftected games all run on a very similar codebase:
* Swedish Touring Car Championship
* Swedish Touring Car Championship 2
* V8 Challenge
* Michelin Rally Masters

![image](https://github.com/elishacloud/dinputto8/assets/7947461/296fb042-7b8c-47c3-bb95-bc4b89a57faf)

I suspect uninitialized data may be fed to the game and I'll try to troubleshoot it myself soon, so I am pretty much leaving this issue as-is here in case you go "Aha, I know what's going on".

EDIT:
Different games are not affected by this, even though they also run inside sandboxes - this could be isolated to a specific `IDirectInput` interface or a specific data format? But a conflict with Sandboxie seems unlikely.

**Comment by elishacloud** [comment]
If I had to guess what the issue is, I suspect it is related to either `SetDataFormat()` or `GetDeviceData()`.  You could add some logging to these functions to see what the game is sending in and what dinputto8 is sending out.

**Comment by CookiePLMonster** [comment]
OK, I'm going to infodump everything I find here, so in case I don't find the reason, it's documented:

* The game uses `IID_IDirectInputW`, version 0x500 and `IID_IDirectInputDevice2W`.
* The game appears to be using a regular `DIJOYSTATE2` for the data format (0x110 bytes big).
* Keyboard and mouse use DInput too, but they are unlikely to be the problem.
* `GetDeviceData()` isn't used, but `GetDeviceState()` is.

Does the version (0x500) matter? You don't seem to be using it anywhere.

Update1:
Seems like the game may be failing to acquire input - I keep getting `DIERR_NOTACQUIRED` on `GetDeviceState()` until I alt+tab the game (making debugging harder, lol). Logs indicate it should keep trying to Acquire, but maybe something is going wrong there.

Update2: ~~Outside of the minimize scenario, I am getting a lot of `E_ACCESSDENIED` on `Acquire`.~~ Although this is not the case when not Alt+Tabbing.

Update3: The game seems to get confused by... the POV hat? It almost works as if the data format that's delivered to dinput doesn't match what is given back. I'll have to check what exact structure they use in `SetDataFormat` since it may not be a normal `DIJOYSTATE2`.

Update4:
I was able to confirm that I can map this controller in the game when `dinputto8` is not in use, by using it on a Win8.1 virtual machine. As expected, I cannot map the POV hat, but face buttons work as expected.

**Comment by CookiePLMonster** [comment]
![image](https://github.com/elishacloud/dinputto8/assets/7947461/ce42c3f6-5831-4938-907b-dd104c4e1158)
Those appear to be `SetProperty` calls that use integers instead of pointers to GUIDs - is this even legal?

**Comment by CookiePLMonster** [comment]
Interesting read:
https://groups.google.com/g/microsoft.public.win32.programmer.directx.input/c/f9b4lvFYj38?pli=1

> The offsets of input device returned by EnumObjects were defined by the
drivers of the devices. They specified the offset of the objects' data in
the data stream reported by the drivers. They were not depending on the data
format setting up by calling IDirectInputDevice8::SetDataFormat.

> In DirectX 7, directinput returned the offset of the objects in the
DIDDATAFORMAT structure (passed to the SetDataFormat). However; DirectX8,
and DirectX9 changed them back to be the same as in DirectX6, and previous
versions.

I can't confirm the DirectX 6 claim (because Rally Masters requests version 0x500), but it does seem a lot like the game expects `EnumObjects` to match `SetDataFormat`. The one "proof" I have so far is that on my gamepad, Y axis is enumerated under offset 0 while X is under an offset 4, and this is exactly how the game names those axes for me - effectively mixing them up, since X axis is the one that belongs to offset 0, and vice versa.

EDIT:
Seems to be a jackpot - dx6.1, 7 and dx8 docs specify that the offset matches `SetDataFormat` if set, otherwise it's raw data. However, dx8.1 and current docs specify it's always raw data - so how did they make this change?` `DIRECTINPUT_VERSION` did not change for dx8.1...

EDIT2:
I'll be running tests against the original dinput today and hopefully PR a fix as soon as possible - I have a few ideas.

**Comment by CookiePLMonster** [comment]
Together with @riverar wrote a small test app that does the following for all known DirectInput versions (excluding 8):
1. Creates a DI object and a DI device for the first found attached device of type `DIDEVTYPE_JOYSTICK`.
2. Enumerates all objects and prints names and offsets.
3. Sets the data format to a very arbitrary format, to make disprepancies obvious:
```cpp
DIOBJECTDATAFORMAT joystick[] = {
	{ &GUID_XAxis, 12, DIDFT_AXIS|DIDFT_ANYINSTANCE, 0 },
	{ &GUID_ZAxis, 0, DIDFT_AXIS|DIDFT_ANYINSTANCE, 0 }
};
```
4. Enumerates all objects again.

The test results (done on Windows 8.1, to avoid a dinput enumeration bug from Win10) are as follows. Click on arrows to expand:
<details>
  <summary>No dinputto8</summary>
Testing version 0x300:

Testing version 0x500:
Found device: Controller (XBOX One For Windows)

Enumerating objects WITHOUT data format set
1. dwOfs=0, tszName=X Axis
2. dwOfs=4, tszName=Y Axis
3. dwOfs=8, tszName=Z Axis
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Y Rotation
6. dwOfs=32, tszName=Hat Switch
7. dwOfs=48, tszName=Button 0
8. dwOfs=49, tszName=Button 1
9. dwOfs=50, tszName=Button 2
10. dwOfs=51, tszName=Button 3
11. dwOfs=52, tszName=Button 4
12. dwOfs=53, tszName=Button 5
13. dwOfs=54, tszName=Button 6
14. dwOfs=55, tszName=Button 7
15. dwOfs=56, tszName=Button 8
16. dwOfs=57, tszName=Button 9

Enumerating objects WITH data format set
1. dwOfs=12, tszName=X Axis
2. dwOfs=-1, tszName=Y Axis
3. dwOfs=0, tszName=Z Axis
4. dwOfs=-1, tszName=X Rotation
5. dwOfs=-1, tszName=Y Rotation
6. dwOfs=-1, tszName=Hat Switch
7. dwOfs=-1, tszName=Button 0
8. dwOfs=-1, tszName=Button 1
9. dwOfs=-1, tszName=Button 2
10. dwOfs=-1, tszName=Button 3
11. dwOfs=-1, tszName=Button 4
12. dwOfs=-1, tszName=Button 5
13. dwOfs=-1, tszName=Button 6
14. dwOfs=-1, tszName=Button 7
15. dwOfs=-1, tszName=Button 8
16. dwOfs=-1, tszName=Button 9


Testing version 0x50a:
Found device: Controller (XBOX One For Windows)

Enumerating objects WITHOUT data format set
1. dwOfs=0, tszName=X Axis
2. dwOfs=4, tszName=Y Axis
3. dwOfs=8, tszName=Z Axis
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Y Rotation
6. dwOfs=32, tszName=Hat Switch
7. dwOfs=48, tszName=Button 0
8. dwOfs=49, tszName=Button 1
9. dwOfs=50, tszName=Button 2
10. dwOfs=51, tszName=Button 3
11. dwOfs=52, tszName=Button 4
12. dwOfs=53, tszName=Button 5
13. dwOfs=54, tszName=Button 6
14. dwOfs=55, tszName=Button 7
15. dwOfs=56, tszName=Button 8
16. dwOfs=57, tszName=Button 9

Enumerating objects WITH data format set
1. dwOfs=12, tszName=X Axis
2. dwOfs=-1, tszName=Y Axis
3. dwOfs=0, tszName=Z Axis
4. dwOfs=-1, tszName=X Rotation
5. dwOfs=-1, tszName=Y Rotation
6. dwOfs=-1, tszName=Hat Switch
7. dwOfs=-1, tszName=Button 0
8. dwOfs=-1, tszName=Button 1
9. dwOfs=-1, tszName=Button 2
10. dwOfs=-1, tszName=Button 3
11. dwOfs=-1, tszName=Button 4
12. dwOfs=-1, tszName=Button 5
13. dwOfs=-1, tszName=Button 6
14. dwOfs=-1, tszName=Button 7
15. dwOfs=-1, tszName=Button 8
16. dwOfs=-1, tszName=Button 9


Testing version 0x5b2:
Found device: Controller (XBOX One For Windows)

Enumerating objects WITHOUT data format set
1. dwOfs=0, tszName=Y Axis
2. dwOfs=4, tszName=X Axis
3. dwOfs=8, tszName=Y Rotation
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Z Axis
6. dwOfs=24, tszName=Button 0
7. dwOfs=25, tszName=Button 1
8. dwOfs=26, tszName=Button 2
9. dwOfs=27, tszName=Button 3
10. dwOfs=28, tszName=Button 4
11. dwOfs=29, tszName=Button 5
12. dwOfs=30, tszName=Button 6
13. dwOfs=31, tszName=Button 7
14. dwOfs=32, tszName=Button 8
15. dwOfs=33, tszName=Button 9
16. dwOfs=20, tszName=Hat Switch
17. dwOfs=0, tszName=Collection 0 - Game Pad
18. dwOfs=0, tszName=Collection 1
19. dwOfs=0, tszName=Collection 2
20. dwOfs=0, tszName=Collection 3

Enumerating objects WITH data format set
1. dwOfs=-1, tszName=Y Axis
2. dwOfs=12, tszName=X Axis
3. dwOfs=-1, tszName=Y Rotation
4. dwOfs=-1, tszName=X Rotation
5. dwOfs=0, tszName=Z Axis
6. dwOfs=-1, tszName=Button 0
7. dwOfs=-1, tszName=Button 1
8. dwOfs=-1, tszName=Button 2
9. dwOfs=-1, tszName=Button 3
10. dwOfs=-1, tszName=Button 4
11. dwOfs=-1, tszName=Button 5
12. dwOfs=-1, tszName=Button 6
13. dwOfs=-1, tszName=Button 7
14. dwOfs=-1, tszName=Button 8
15. dwOfs=-1, tszName=Button 9
16. dwOfs=-1, tszName=Hat Switch
17. dwOfs=-1, tszName=Collection 0 - Game Pad
18. dwOfs=-1, tszName=Collection 1
19. dwOfs=-1, tszName=Collection 2
20. dwOfs=-1, tszName=Collection 3


Testing version 0x602:
Found device: Controller (XBOX One For Windows)

Enumerating objects WITHOUT data format set
1. dwOfs=0, tszName=X Axis
2. dwOfs=4, tszName=Y Axis
3. dwOfs=8, tszName=Z Axis
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Y Rotation
6. dwOfs=32, tszName=Hat Switch
7. dwOfs=48, tszName=Button 0
8. dwOfs=49, tszName=Button 1
9. dwOfs=50, tszName=Button 2
10. dwOfs=51, tszName=Button 3
11. dwOfs=52, tszName=Button 4
12. dwOfs=53, tszName=Button 5
13. dwOfs=54, tszName=Button 6
14. dwOfs=55, tszName=Button 7
15. dwOfs=56, tszName=Button 8
16. dwOfs=57, tszName=Button 9

Enumerating objects WITH data format set
1. dwOfs=12, tszName=X Axis
2. dwOfs=-1, tszName=Y Axis
3. dwOfs=0, tszName=Z Axis
4. dwOfs=-1, tszName=X Rotation
5. dwOfs=-1, tszName=Y Rotation
6. dwOfs=-1, tszName=Hat Switch
7. dwOfs=-1, tszName=Button 0
8. dwOfs=-1, tszName=Button 1
9. dwOfs=-1, tszName=Button 2
10. dwOfs=-1, tszName=Button 3
11. dwOfs=-1, tszName=Button 4
12. dwOfs=-1, tszName=Button 5
13. dwOfs=-1, tszName=Button 6
14. dwOfs=-1, tszName=Button 7
15. dwOfs=-1, tszName=Button 8
16. dwOfs=-1, tszName=Button 9


Testing version 0x61a:
Found device: Controller (XBOX One For Windows)

Enumerating objects WITHOUT data format set
1. dwOfs=0, tszName=X Axis
2. dwOfs=4, tszName=Y Axis
3. dwOfs=8, tszName=Z Axis
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Y Rotation
6. dwOfs=32, tszName=Hat Switch
7. dwOfs=48, tszName=Button 0
8. dwOfs=49, tszName=Button 1
9. dwOfs=50, tszName=Button 2
10. dwOfs=51, tszName=Button 3
11. dwOfs=52, tszName=Button 4
12. dwOfs=53, tszName=Button 5
13. dwOfs=54, tszName=Button 6
14. dwOfs=55, tszName=Button 7
15. dwOfs=56, tszName=Button 8
16. dwOfs=57, tszName=Button 9

Enumerating objects WITH data format set
1. dwOfs=12, tszName=X Axis
2. dwOfs=-1, tszName=Y Axis
3. dwOfs=0, tszName=Z Axis
4. dwOfs=-1, tszName=X Rotation
5. dwOfs=-1, tszName=Y Rotation
6. dwOfs=-1, tszName=Hat Switch
7. dwOfs=-1, tszName=Button 0
8. dwOfs=-1, tszName=Button 1
9. dwOfs=-1, tszName=Button 2
10. dwOfs=-1, tszName=Button 3
11. dwOfs=-1, tszName=Button 4
12. dwOfs=-1, tszName=Button 5
13. dwOfs=-1, tszName=Button 6
14. dwOfs=-1, tszName=Button 7
15. dwOfs=-1, tszName=Button 8
16. dwOfs=-1, tszName=Button 9


Testing version 0x700:
Found device: Controller (XBOX One For Windows)

Enumerating objects WITHOUT data format set
1. dwOfs=0, tszName=Y Axis
2. dwOfs=4, tszName=X Axis
3. dwOfs=8, tszName=Y Rotation
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Z Axis
6. dwOfs=24, tszName=Button 0
7. dwOfs=25, tszName=Button 1
8. dwOfs=26, tszName=Button 2
9. dwOfs=27, tszName=Button 3
10. dwOfs=28, tszName=Button 4
11. dwOfs=29, tszName=Button 5
12. dwOfs=30, tszName=Button 6
13. dwOfs=31, tszName=Button 7
14. dwOfs=32, tszName=Button 8
15. dwOfs=33, tszName=Button 9
16. dwOfs=20, tszName=Hat Switch
17. dwOfs=0, tszName=Collection 0 - Game Pad
18. dwOfs=0, tszName=Collection 1
19. dwOfs=0, tszName=Collection 2
20. dwOfs=0, tszName=Collection 3

Enumerating objects WITH data format set
1. dwOfs=-1, tszName=Y Axis
2. dwOfs=12, tszName=X Axis
3. dwOfs=-1, tszName=Y Rotation
4. dwOfs=-1, tszName=X Rotation
5. dwOfs=0, tszName=Z Axis
6. dwOfs=-1, tszName=Button 0
7. dwOfs=-1, tszName=Button 1
8. dwOfs=-1, tszName=Button 2
9. dwOfs=-1, tszName=Button 3
10. dwOfs=-1, tszName=Button 4
11. dwOfs=-1, tszName=Button 5
12. dwOfs=-1, tszName=Button 6
13. dwOfs=-1, tszName=Button 7
14. dwOfs=-1, tszName=Button 8
15. dwOfs=-1, tszName=Button 9
16. dwOfs=-1, tszName=Hat Switch
17. dwOfs=-1, tszName=Collection 0 - Game Pad
18. dwOfs=-1, tszName=Collection 1
19. dwOfs=-1, tszName=Collection 2
20. dwOfs=-1, tszName=Collection 3
</details>

<details>
  <summary>With dinputto8</summary>
Testing version 0x300:
Found device: Controller (XBOX One For Windows)

Enumerating objects WITHOUT data format set
1. dwOfs=0, tszName=Y Axis
2. dwOfs=4, tszName=X Axis
3. dwOfs=8, tszName=Y Rotation
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Z Axis
6. dwOfs=24, tszName=Button 0
7. dwOfs=25, tszName=Button 1
8. dwOfs=26, tszName=Button 2
9. dwOfs=27, tszName=Button 3
10. dwOfs=28, tszName=Button 4
11. dwOfs=29, tszName=Button 5
12. dwOfs=30, tszName=Button 6
13. dwOfs=31, tszName=Button 7
14. dwOfs=32, tszName=Button 8
15. dwOfs=33, tszName=Button 9
16. dwOfs=20, tszName=Hat Switch
17. dwOfs=0, tszName=Collection 0 - Game Pad
18. dwOfs=0, tszName=Collection 1
19. dwOfs=0, tszName=Collection 2
20. dwOfs=0, tszName=Collection 3

Enumerating objects WITH data format set
1. dwOfs=0, tszName=Y Axis
2. dwOfs=4, tszName=X Axis
3. dwOfs=8, tszName=Y Rotation
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Z Axis
6. dwOfs=24, tszName=Button 0
7. dwOfs=25, tszName=Button 1
8. dwOfs=26, tszName=Button 2
9. dwOfs=27, tszName=Button 3
10. dwOfs=28, tszName=Button 4
11. dwOfs=29, tszName=Button 5
12. dwOfs=30, tszName=Button 6
13. dwOfs=31, tszName=Button 7
14. dwOfs=32, tszName=Button 8
15. dwOfs=33, tszName=Button 9
16. dwOfs=20, tszName=Hat Switch
17. dwOfs=0, tszName=Collection 0 - Game Pad
18. dwOfs=0, tszName=Collection 1
19. dwOfs=0, tszName=Collection 2
20. dwOfs=0, tszName=Collection 3


Testing version 0x500:
Found device: Controller (XBOX One For Windows)

Enumerating objects WITHOUT data format set
1. dwOfs=0, tszName=Y Axis
2. dwOfs=4, tszName=X Axis
3. dwOfs=8, tszName=Y Rotation
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Z Axis
6. dwOfs=24, tszName=Button 0
7. dwOfs=25, tszName=Button 1
8. dwOfs=26, tszName=Button 2
9. dwOfs=27, tszName=Button 3
10. dwOfs=28, tszName=Button 4
11. dwOfs=29, tszName=Button 5
12. dwOfs=30, tszName=Button 6
13. dwOfs=31, tszName=Button 7
14. dwOfs=32, tszName=Button 8
15. dwOfs=33, tszName=Button 9
16. dwOfs=20, tszName=Hat Switch
17. dwOfs=0, tszName=Collection 0 - Game Pad
18. dwOfs=0, tszName=Collection 1
19. dwOfs=0, tszName=Collection 2
20. dwOfs=0, tszName=Collection 3

Enumerating objects WITH data format set
1. dwOfs=0, tszName=Y Axis
2. dwOfs=4, tszName=X Axis
3. dwOfs=8, tszName=Y Rotation
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Z Axis
6. dwOfs=24, tszName=Button 0
7. dwOfs=25, tszName=Button 1
8. dwOfs=26, tszName=Button 2
9. dwOfs=27, tszName=Button 3
10. dwOfs=28, tszName=Button 4
11. dwOfs=29, tszName=Button 5
12. dwOfs=30, tszName=Button 6
13. dwOfs=31, tszName=Button 7
14. dwOfs=32, tszName=Button 8
15. dwOfs=33, tszName=Button 9
16. dwOfs=20, tszName=Hat Switch
17. dwOfs=0, tszName=Collection 0 - Game Pad
18. dwOfs=0, tszName=Collection 1
19. dwOfs=0, tszName=Collection 2
20. dwOfs=0, tszName=Collection 3


Testing version 0x50a:
Found device: Controller (XBOX One For Windows)

Enumerating objects WITHOUT data format set
1. dwOfs=0, tszName=Y Axis
2. dwOfs=4, tszName=X Axis
3. dwOfs=8, tszName=Y Rotation
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Z Axis
6. dwOfs=24, tszName=Button 0
7. dwOfs=25, tszName=Button 1
8. dwOfs=26, tszName=Button 2
9. dwOfs=27, tszName=Button 3
10. dwOfs=28, tszName=Button 4
11. dwOfs=29, tszName=Button 5
12. dwOfs=30, tszName=Button 6
13. dwOfs=31, tszName=Button 7
14. dwOfs=32, tszName=Button 8
15. dwOfs=33, tszName=Button 9
16. dwOfs=20, tszName=Hat Switch
17. dwOfs=0, tszName=Collection 0 - Game Pad
18. dwOfs=0, tszName=Collection 1
19. dwOfs=0, tszName=Collection 2
20. dwOfs=0, tszName=Collection 3

Enumerating objects WITH data format set
1. dwOfs=0, tszName=Y Axis
2. dwOfs=4, tszName=X Axis
3. dwOfs=8, tszName=Y Rotation
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Z Axis
6. dwOfs=24, tszName=Button 0
7. dwOfs=25, tszName=Button 1
8. dwOfs=26, tszName=Button 2
9. dwOfs=27, tszName=Button 3
10. dwOfs=28, tszName=Button 4
11. dwOfs=29, tszName=Button 5
12. dwOfs=30, tszName=Button 6
13. dwOfs=31, tszName=Button 7
14. dwOfs=32, tszName=Button 8
15. dwOfs=33, tszName=Button 9
16. dwOfs=20, tszName=Hat Switch
17. dwOfs=0, tszName=Collection 0 - Game Pad
18. dwOfs=0, tszName=Collection 1
19. dwOfs=0, tszName=Collection 2
20. dwOfs=0, tszName=Collection 3


Testing version 0x5b2:
Found device: Controller (XBOX One For Windows)

Enumerating objects WITHOUT data format set
1. dwOfs=0, tszName=Y Axis
2. dwOfs=4, tszName=X Axis
3. dwOfs=8, tszName=Y Rotation
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Z Axis
6. dwOfs=24, tszName=Button 0
7. dwOfs=25, tszName=Button 1
8. dwOfs=26, tszName=Button 2
9. dwOfs=27, tszName=Button 3
10. dwOfs=28, tszName=Button 4
11. dwOfs=29, tszName=Button 5
12. dwOfs=30, tszName=Button 6
13. dwOfs=31, tszName=Button 7
14. dwOfs=32, tszName=Button 8
15. dwOfs=33, tszName=Button 9
16. dwOfs=20, tszName=Hat Switch
17. dwOfs=0, tszName=Collection 0 - Game Pad
18. dwOfs=0, tszName=Collection 1
19. dwOfs=0, tszName=Collection 2
20. dwOfs=0, tszName=Collection 3

Enumerating objects WITH data format set
1. dwOfs=0, tszName=Y Axis
2. dwOfs=4, tszName=X Axis
3. dwOfs=8, tszName=Y Rotation
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Z Axis
6. dwOfs=24, tszName=Button 0
7. dwOfs=25, tszName=Button 1
8. dwOfs=26, tszName=Button 2
9. dwOfs=27, tszName=Button 3
10. dwOfs=28, tszName=Button 4
11. dwOfs=29, tszName=Button 5
12. dwOfs=30, tszName=Button 6
13. dwOfs=31, tszName=Button 7
14. dwOfs=32, tszName=Button 8
15. dwOfs=33, tszName=Button 9
16. dwOfs=20, tszName=Hat Switch
17. dwOfs=0, tszName=Collection 0 - Game Pad
18. dwOfs=0, tszName=Collection 1
19. dwOfs=0, tszName=Collection 2
20. dwOfs=0, tszName=Collection 3


Testing version 0x602:
Found device: Controller (XBOX One For Windows)

Enumerating objects WITHOUT data format set
1. dwOfs=0, tszName=Y Axis
2. dwOfs=4, tszName=X Axis
3. dwOfs=8, tszName=Y Rotation
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Z Axis
6. dwOfs=24, tszName=Button 0
7. dwOfs=25, tszName=Button 1
8. dwOfs=26, tszName=Button 2
9. dwOfs=27, tszName=Button 3
10. dwOfs=28, tszName=Button 4
11. dwOfs=29, tszName=Button 5
12. dwOfs=30, tszName=Button 6
13. dwOfs=31, tszName=Button 7
14. dwOfs=32, tszName=Button 8
15. dwOfs=33, tszName=Button 9
16. dwOfs=20, tszName=Hat Switch
17. dwOfs=0, tszName=Collection 0 - Game Pad
18. dwOfs=0, tszName=Collection 1
19. dwOfs=0, tszName=Collection 2
20. dwOfs=0, tszName=Collection 3

Enumerating objects WITH data format set
1. dwOfs=0, tszName=Y Axis
2. dwOfs=4, tszName=X Axis
3. dwOfs=8, tszName=Y Rotation
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Z Axis
6. dwOfs=24, tszName=Button 0
7. dwOfs=25, tszName=Button 1
8. dwOfs=26, tszName=Button 2
9. dwOfs=27, tszName=Button 3
10. dwOfs=28, tszName=Button 4
11. dwOfs=29, tszName=Button 5
12. dwOfs=30, tszName=Button 6
13. dwOfs=31, tszName=Button 7
14. dwOfs=32, tszName=Button 8
15. dwOfs=33, tszName=Button 9
16. dwOfs=20, tszName=Hat Switch
17. dwOfs=0, tszName=Collection 0 - Game Pad
18. dwOfs=0, tszName=Collection 1
19. dwOfs=0, tszName=Collection 2
20. dwOfs=0, tszName=Collection 3


Testing version 0x61a:
Found device: Controller (XBOX One For Windows)

Enumerating objects WITHOUT data format set
1. dwOfs=0, tszName=Y Axis
2. dwOfs=4, tszName=X Axis
3. dwOfs=8, tszName=Y Rotation
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Z Axis
6. dwOfs=24, tszName=Button 0
7. dwOfs=25, tszName=Button 1
8. dwOfs=26, tszName=Button 2
9. dwOfs=27, tszName=Button 3
10. dwOfs=28, tszName=Button 4
11. dwOfs=29, tszName=Button 5
12. dwOfs=30, tszName=Button 6
13. dwOfs=31, tszName=Button 7
14. dwOfs=32, tszName=Button 8
15. dwOfs=33, tszName=Button 9
16. dwOfs=20, tszName=Hat Switch
17. dwOfs=0, tszName=Collection 0 - Game Pad
18. dwOfs=0, tszName=Collection 1
19. dwOfs=0, tszName=Collection 2
20. dwOfs=0, tszName=Collection 3

Enumerating objects WITH data format set
1. dwOfs=0, tszName=Y Axis
2. dwOfs=4, tszName=X Axis
3. dwOfs=8, tszName=Y Rotation
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Z Axis
6. dwOfs=24, tszName=Button 0
7. dwOfs=25, tszName=Button 1
8. dwOfs=26, tszName=Button 2
9. dwOfs=27, tszName=Button 3
10. dwOfs=28, tszName=Button 4
11. dwOfs=29, tszName=Button 5
12. dwOfs=30, tszName=Button 6
13. dwOfs=31, tszName=Button 7
14. dwOfs=32, tszName=Button 8
15. dwOfs=33, tszName=Button 9
16. dwOfs=20, tszName=Hat Switch
17. dwOfs=0, tszName=Collection 0 - Game Pad
18. dwOfs=0, tszName=Collection 1
19. dwOfs=0, tszName=Collection 2
20. dwOfs=0, tszName=Collection 3


Testing version 0x700:
Found device: Controller (XBOX One For Windows)

Enumerating objects WITHOUT data format set
1. dwOfs=0, tszName=Y Axis
2. dwOfs=4, tszName=X Axis
3. dwOfs=8, tszName=Y Rotation
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Z Axis
6. dwOfs=24, tszName=Button 0
7. dwOfs=25, tszName=Button 1
8. dwOfs=26, tszName=Button 2
9. dwOfs=27, tszName=Button 3
10. dwOfs=28, tszName=Button 4
11. dwOfs=29, tszName=Button 5
12. dwOfs=30, tszName=Button 6
13. dwOfs=31, tszName=Button 7
14. dwOfs=32, tszName=Button 8
15. dwOfs=33, tszName=Button 9
16. dwOfs=20, tszName=Hat Switch
17. dwOfs=0, tszName=Collection 0 - Game Pad
18. dwOfs=0, tszName=Collection 1
19. dwOfs=0, tszName=Collection 2
20. dwOfs=0, tszName=Collection 3

Enumerating objects WITH data format set
1. dwOfs=0, tszName=Y Axis
2. dwOfs=4, tszName=X Axis
3. dwOfs=8, tszName=Y Rotation
4. dwOfs=12, tszName=X Rotation
5. dwOfs=16, tszName=Z Axis
6. dwOfs=24, tszName=Button 0
7. dwOfs=25, tszName=Button 1
8. dwOfs=26, tszName=Button 2
9. dwOfs=27, tszName=Button 3
10. dwOfs=28, tszName=Button 4
11. dwOfs=29, tszName=Button 5
12. dwOfs=30, tszName=Button 6
13. dwOfs=31, tszName=Button 7
14. dwOfs=32, tszName=Button 8
15. dwOfs=33, tszName=Button 9
16. dwOfs=20, tszName=Hat Switch
17. dwOfs=0, tszName=Collection 0 - Game Pad
18. dwOfs=0, tszName=Collection 1
19. dwOfs=0, tszName=Collection 2
20. dwOfs=0, tszName=Collection 3
</details>

A number of behaviour differences is observable:
1. Version 0x300 doesn't even appear to enumerate any joysticks.
2. As per the above post, **all** versions seem to respect the call to `SetDataFormat` in terms of offsets they report, and they report a `-1` offset if the data format does not include a specific device object. However, this call does not influence the **order** of objects, and knowing how weird games can be, they may be relying on this order too.
3. DInput versions that are not `0x700` or `0x5b2` do not report `Collection X` objects, whatever they are.
4. Order of enumerated objects and offsets differ between version, with versions  `0x700` and `0x5b2` matching dinputto8, while the rest doesn't. Looking at the structure of `DIJOYSTATE`, it seems obvious that those other versions follow the order and offsets from that struct.

For lack of better ideas, I suggest dinputto8 reorders "affected" enumeration calls to reflect the layout of `DIJOYSTATE` (for gamepads at least). The remaining changes required (set offset to `-1` if object is not present in the data format etc.) seem more obvious. I am not 100% sure this is the correct approach, but it should be close enough and it'll already be a huge improvement over the current state of affairs, where dinput8 behaviour leaks to applications in multiple ways.

I'll be PR'ing those changes soon.

**Comment by elishacloud** [comment]
Great!  Thanks for looking into this @CookiePLMonster.

**Comment by elishacloud** [comment]
@CookiePLMonster, I integrated the fixes and published a new release.  I had some issues uploading the build to GitHub.  Please check out the release and let me know if you have any issues.

**Comment by CookiePLMonster** [comment]
I tested on Need for Speed Porsche, as well as one of the games affected by this bug and everything is in order. Thanks!

**Comment by elishacloud** [comment]
Thanks @CookiePLMonster!
