### ISSUE TITLE
[Rayman 2] No input is recognised

### ISSUE THREAD

**Issue by RibShark** [elishacloud/dinputto8#2]
When attempting to use the wrapper with Rayman 2, no input is recognised either from the keyboard or from a gamepad. I tried both the pre-release build and my own build with the latest commits.

Log file: 
```11460 16:46:10.749 Starting dinputto8 v1.0.12.0
11460 16:46:14.795 To Be Filled By O.E.M. To Be Filled By O.E.M. To Be Filled By O.E.M. (Desktop)
11460 16:46:14.795 ASRock H97M Pro4                        (Desktop)
11460 16:46:14.795 Windows 10 64-bit (10.0.17763)
11460 16:46:14.795 "Rayman2.exe" (PID:6404)
11460 16:46:14.797 Redirecting 'DirectInputCreate' IID_IDirectInputA version 0x500 to --> 'DirectInput8Create'

**Comment by elishacloud** [comment]
Yeah, I saw this with another game also which is why I have not released it yet.  I will take a look at it.  Thanks!

**Comment by RibShark** [comment]
I believe the issue lies in the differences between the dwDevType member of the DIDEVICEINSTANCE structure. In dinput, DIDEVTYPE_MOUSE, DIDEVTYPE_KEYBOARD and DIDEVTYPE_JOYSTICK are 0x2, 0x3 and 0x4 respectively, while in dinput8, DI8DEVTYPE_MOUSE, DI8DEVTYPE_KEYBOARD and DI8DEVTYPE_JOYSTICK are 0x12, 0x13 and 0x14 respectively.

This causes code such as the following used in Rayman 2's EnumDevices callback to fail:
```
switch ( LOBYTE(pdinst->dwDevType) )
  {
    case DIDEVTYPE_MOUSE:
      pdidf = &dfDIMouse;
      break;
    case DIDEVTYPE_KEYBOARD:
      pdidf = &dfDIKeyboard;
      break;
    case DIDEVTYPE_JOYSTICK:
      pdidf = &dfDIJoystick;
      break;
    default:
      return 0;
  }
```
Please do correct me if I'm wrong, I'm not an expert at DirectInput by any means, but this is what I have observed.

**Comment by elishacloud** [comment]
Yes, the issue was with the DevType.  I put a fix in for this.  Attached is fixed build: [dinput.zip](https://github.com/elishacloud/dinputto8/files/2863617/dinput.zip)

**Comment by RibShark** [comment]
Thanks, this works perfectly now!
