### ISSUE TITLE
Polaris SnoCross crashes at startup

### ISSUE THREAD

**Issue by NicknineTheEagle** [elishacloud/dinputto8#24]
Was hoping to use dinputto8 + devreorder to work around a bug with device enumeration in this game but dinputto8 doesn't seem work properly causing a startup crash. From looking with the debugger, it looks like IDirectInputDevice2A::GetCapabilities returns garbage data.

Log:
```
18804 23:38:48.111 Starting dinputto8 v1.0.54.0
18804 23:38:48.111 ASUSTeK COMPUTER INC. VivoBook_ASUSLaptop X513EAN_F513EA 1.0        (Notebook)
18804 23:38:48.111 ASUSTeK COMPUTER INC. X513EAN 1.0        (Notebook)
18804 23:38:48.112 Windows 10 Enterprise 64-bit (10.0.19041)
18804 23:38:48.112 SnoCross.exe (PID:13712)
18804 23:38:48.117 DirectInputCreateA
18804 23:38:48.117 DirectInputCreateEx
18804 23:38:48.117 Redirecting 'DirectInputCreate' IID_IDirectInputA version 0x500 to --> 'DirectInput8Create'
18804 23:38:48.126 Creating interface m_IDirectInputX::m_IDirectInputX(007BF620) converting interface from v1 to v8 using ANSI
18804 23:38:48.126 m_IDirectInputX::EnumDevicesX (007BF620)
18804 23:38:48.130 m_IDirectInputX::CreateDeviceExX (007BF620)
18804 23:38:48.130 Creating interface m_IDirectInputDeviceX::m_IDirectInputDeviceX(007A2A90) converting interface from v1 to v8 using ANSI
18804 23:38:48.130 m_IDirectInputDeviceX::QueryInterface (007A2A90)
18804 23:38:48.130 dinputto8::ProxyQueryInterface Query for IID_IDirectInputDevice2A from IID_IDirectInputDevice2A
18804 23:38:48.130 m_IDirectInputDeviceX::AddRef (007A2A90)
18804 23:38:48.130 m_IDirectInputDeviceX::Release (007A2A90)
18804 23:38:48.130 m_IDirectInputDeviceX::GetCapabilities (007A2A90)
18804 23:38:48.130 m_IDirectInputDeviceX::GetDeviceInfoX (007A2A90)
```

**Comment by elishacloud** [comment]
Can you try removing all joysticks and gamepads and try again?  I am wondering if the issue is related to the game or a controller that is attached.

**Comment by NicknineTheEagle** [comment]
Already tried that, no change. Note that it crashes on the very first device parsed which is the mouse.

**Comment by elishacloud** [comment]
Ok, I added some checks to `GetCapabilities()` to help make sure that appropriate data is returned.

Can you try with this build:  [dinput.zip](https://github.com/elishacloud/dinputto8/files/15477548/dinput.zip)

**Comment by NicknineTheEagle** [comment]
No change, still crashes. Actually, I'm looking at it more and it looks like DIDEVCAPS.dwDevType contains DI8 values which are invalid for DI7 and below. It's set to 0x00000413 which is DI8DEVTYPE_KEYBOARD and DI8DEVTYPEKEYBOARD_PCENH. DI7 and below should return old constants which would be DIDEVTYPE_KEYBOARD and DIDEVTYPEKEYBOARD_PCENH in this particular case. `m_IDirectInputDeviceX::GetCapabilities` needs to convert dwDevType just like `m_IDirectInputDeviceX::GetDeviceInfoX` already does.
