### ISSUE TITLE
Winmm to Dinput8 please?

### ISSUE THREAD

**Issue by v00d00m4n** [elishacloud/dinputto8#3]
Older games used Winmm prior Dinput, some modern games for some stupid reason still use it, like infamouse Deadly Premonition, for example.

**Comment by elishacloud** [comment]
Great idea.  I will look into this later.  Probably won't be for a while since I have a lot of stuff on my plate now.

**Comment by elishacloud** [comment]
There is a tool that was created to help compatibility with winmm games.  Checkout this tool: [Xidi](https://github.com/samuelgr/Xidi)

**Comment by elishacloud** [comment]
Closing issue.
