### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by dosinabox** [elishacloud/dinputto8#5]
Is it possible to disable logging to dinput.log? Or can you please create such dxinput.dll with disabled logging?

**Comment by elishacloud** [comment]
In the next update logging will be disabled in the release build.  In the mean time, here is a version that has logging disabled:  [dinput.zip](https://github.com/elishacloud/dinputto8/files/4126091/dinput.zip)

**Comment by dosinabox** [comment]
Thank you very much!
