### ISSUE TITLE
Lightshot conflict?

### ISSUE THREAD

**Issue by dosinabox** [elishacloud/dinputto8#7]
It appears that dinputto8 is blocking Lightshot program in both Gothic and Gothic 2 games - can't take screenshots. It's working again if I remove dinput.dll file from game's /system folder. I'm using the latest 5.5.0.4 version of Lightshot and the latest 1.0.30.0 version of dinputto8.
Why would I need dinputto8 in Gothic and Gothic 2? Otherwise mouse is not moving in Steam Overlay.

**Comment by elishacloud** [comment]
This is interesting.  I would not think that Lightshot has anything to do with DirectInput.  I will take a look at this when I get a chance.  So far I have been pretty busy.

> Why would I need dinputto8 in Gothic and Gothic 2? Otherwise mouse is not moving in Steam Overlay.

Yeah, Steam overlay probably requires DirectInput 8.  That is an example of why I created this.

**Comment by elishacloud** [comment]
@dosinabox, can you try with this build and let me know the results?

Testing build: [dinput.zip](https://github.com/elishacloud/dinputto8/files/4863821/dinput.zip)

**Comment by elishacloud** [comment]
Closing issue.
