### ISSUE TITLE
Force Feedback request

### ISSUE THREAD

**Issue by luca2125** [elishacloud/dinputto8#8]
Hi,

I have multiple devices (Microsoft Sidewinder FFB 2, pedals, throttle, etc..) and most games don't allow to use more than one device.

To solve this problem I use vjoy that work fine for this, but unfortunatenly the games detect vjoy as 
 priimary Force Feeback device and not  my real device Microsoft Sidewinder Force Feedback.

The final result is that the force feedback not work becouse the games send all effects to vjoy and not to my Sidewinder FFB 2 that is the real device.

I ask if is possible redirect all FFB effecs only to a real device (lìke my Sidewinder Force Feedback for example)  and never to a virtual device (like vjoy for example)

Is possible do it ?

**Comment by elishacloud** [comment]
@luca2125, you are probably looking for a DirectInput8 wrapper.  This wrapper just converts DirectInput to DirectInput8.  Adding features like this is not something I am planning to do on this project.

You can probably contact vJoy directly and ask them to help.  Here is the link:  [https://vjoy.freeforums.net/](https://vjoy.freeforums.net/)
